### ISSUE TITLE
/bin/sh -c ./build_hss_rel14 --check-installed-software --force' returned a non-zero code

### ISSUE THREAD

**Issue by Sivanesh1992** [OPENAIRINTERFACE/openair-epc-fed#29]
Hi ,
 i am unable to build HSS having below error 
openair-hss/scripts/../build/tools/build_helper.hss_rel14: line 59: ./buildconf: No such file or directory
/openair-hss
Error: HSS software installation failed
The command '/bin/sh -c ./build_hss_rel14 --check-installed-software --force' returned a non-zero code: 1

please anyone suggest steps to resolve the issue

**Comment by Sivanesh1992** [comment]
..

**Comment by me0127** [comment]
> ..
@Sivanesh1992 may i know how this error has be resolved ? since we are also facing same issue.

![image](https://github.com/OPENAIRINTERFACE/openair-epc-fed/assets/154493187/dd502038-ec71-461b-9011-8eece3778c59)
